sudo: required
dist: trusty
language: generic
env:
  global:
    - CONTAINER=forgottenserver
  matrix:
    - LUAJIT=OFF CXX=g++
    - LUAJIT=ON  CXX=g++
    - LUAJIT=OFF CXX=clang++
    - LUAJIT=ON  CXX=clang++
services:
  - docker
install: docker build -t ${CONTAINER} .
before_script: mkdir ${TRAVIS_BUILD_DIR}/build
script:
  - DOCKER_PARAMS="-e CXX=${CXX} -v ${TRAVIS_BUILD_DIR}:/opt -w /opt/build ${CONTAINER}"
  - docker run ${DOCKER_PARAMS} cmake -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=${LUAJIT} ..
  - docker run ${DOCKER_PARAMS} make -j2
